### ISSUE TITLE
Bug: Find without findings throws

### ISSUE THREAD

**Issue by lkuendig** [jsverse/transloco-keys-manager#161]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is this a regression?

Yes

### Current behavior

We have no findings (no missing keys, no extra keys). When I run `transloco-keys-manager find --translations-path assets/i18n/merged` I get the exception:

C:\workarea\services\***\ui\node_modules\@ngneat\transloco-keys-manager\keys-detective\map-diff-to-keys.js:14
    return keys.join('\n');
                ^

TypeError: keys.join is not a function
    at mapDiffToKeys (C:\workarea\services\***\ui\node_modules\@ngneat\transloco-keys-manager\keys-detective\map-diff-to-keys.js:14:17)
    at buildTable (C:\workarea\services\***\ui\node_modules\@ngneat\transloco-keys-manager\keys-detective\build-table.js:40:63)
    at compareKeysToFiles (C:\workarea\services\***\ui\node_modules\@ngneat\transloco-keys-manager\keys-detective\compare-keys-to-files.js:94:34)
    at findMissingKeys (C:\workarea\services\***\ui\node_modules\@ngneat\transloco-keys-manager\keys-detective\index.js:26:52)
    at Object.<anonymous> (C:\workarea\services\***\ui\node_modules\@ngneat\transloco-keys-manager\index.js:38:42)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)

### Expected behavior

Find does not throw when all keys are fine

### Please provide a link to a minimal reproduction of the bug

None

### Please provide the environment you discovered this bug in

```markdown
Transloco: 
Transloco Keys Manager:
Angular:
Node: 
Package Manager: 
OS:
```

### I would like to make a pull request for this bug

No

**Comment by shaharkazaz** [comment]
@lkuendig You are welcome to open a PR

**Comment by lkuendig** [comment]
@shaharkazaz I accidentally deleted the PR (first PR on github :)). can you add those 2 changes https://github.com/ngneat/transloco-keys-manager/pull/162/files. It's only a small bug/fix in case one has `"key": {}` somewhere in the translations

**Comment by shaharkazaz** [comment]
Resolved via [this commit](https://github.com/jsverse/transloco-keys-manager/commit/dd47f5fb#diff-8623d979ed1961e14c9cbf65c46f1a7d4204639cd016380c55c98512b59b7280)
